services:
  # 前端项目
  blog:
    container_name: blog
    build: program/blog
    hostname: blog.thrive.site
    ports:
      - "9001:9001"
    networks:
      thrive_network:
        ipv4_address: 172.178.178.12
    environment:
      # 设置后端接口地址,http://你的后端域名/api
      NEXT_PUBLIC_PROJECT_API: "NEXT_PUBLIC_PROJECT_API_VALUE"
      # 高德地图key
      NEXT_PUBLIC_GAODE_KEY_CODE: "NEXT_PUBLIC_GAODE_KEY_CODE_VALUE"
      # 高德地图秘钥
      NEXT_PUBLIC_GAODE_SECURITYJS_CODE: "NEXT_PUBLIC_GAODE_SECURITYJS_CODE_VALUE"
    depends_on:
      - server

  # 控制端项目
  admin:
    container_name: admin
    build: program/admin
    hostname: admin.thrive.site
    ports:
      - "9002:80"
    networks:
      thrive_network:
        ipv4_address: 172.178.178.13
    environment:
      # 设置后端接口地址,http://你的后端域名/api
      VITE_PROJECT_API: VITE_PROJECT_API_VALUE
      # 百度统计站点ID
      VITE_BAIDU_TONGJI_SITE_ID: "VITE_BAIDU_TONGJI_SITE_ID_VALUE"
      # 百度统计秘钥
      VITE_BAIDU_TONGJI_ACCESS_TOKEN: "VITE_BAIDU_TONGJI_ACCESS_TOKEN_VALUE"
      ## AI大模型秘钥
      VITE_AI_APIPassword: "VITE_AI_APIPassword_VALUE"
      ## 高德地图坐标秘钥
      VITE_GAODE_WEB_API: "VITE_GAODE_WEB_API_VALUE"
    depends_on:
      - server

  # 后端项目
  server:
    container_name: server
    build: registry.cn-hangzhou.aliyuncs.com/thrive/server
    hostname: server.thrive.site
    ports:
      - "9003:9003"
    networks:
      thrive_network:
        ipv4_address: 172.178.178.14
    environment:
      ## 设置数据库主机地址
      DB_INFO: DbHost:Port3306/DbNameThriveX
      ## 设置数据库名,强烈建议修改(首次启动有效)-必须和前面的数据库名一致
      DB_NAME: DbNameThriveX
      ## 设置数据库用户名,强烈建议修改(首次启动有效)-必须和前面的数据库用户名一致
      DB_USERNAME: DbUserThrive
      ## 设置数据库密码,强烈建议修改(首次启动有效)-必须和前面的数据库用户名一致
      DB_PASSWORD: DB_PASSWORD_ThriveX@123?
      ## 设置数据库端口
      DB_PORT: Port3306
      ## 设置邮箱配置
      EMAIL_HOST: smtp.qq.com
      ## 设置邮箱端口
      EMAIL_PORT: 465
      ## 设置邮箱用户名
      EMAIL_USERNAME: 123456789@qq.com
      ## 设置邮箱密码
      EMAIL_PASSWORD: 123456789Password
# 网络配置
networks:
  thrive_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.178.178.0/24